'use client'

import Head from 'next/head'
import './globals.css'
import type { Metadata } from 'next'
import { withFork } from 'effector-next'
import Document from 'next/document'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/img/logo.svg',
  },
}

// const enhance = withFork({ debug: false })

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <Head>
        <link rel="icon" href={'/img/logo.svg'} />
      </Head>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
